// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup_lock.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const acquireBackupLock = `-- name: AcquireBackupLock :execrows
UPDATE backup_lock SET running = true, started_at = NOW(), owner_token = NULL
WHERE id = 1 AND (NOT running OR started_at <= NOW() - INTERVAL '30 minutes')
`

func (q *Queries) AcquireBackupLock(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireBackupLock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const acquireMaintenanceLockForTask = `-- name: AcquireMaintenanceLockForTask :execrows
UPDATE backup_lock SET running = true, started_at = NOW(), owner_token = $1
WHERE id = 1 AND (NOT running OR started_at <= NOW() - INTERVAL '30 minutes')
`

func (q *Queries) AcquireMaintenanceLockForTask(ctx context.Context, ownerToken uuid.NullUUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireMaintenanceLockForTask, ownerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const isBackupLocked = `-- name: IsBackupLocked :one
SELECT CASE WHEN is_maintenance_lock_held() THEN 1 ELSE 0 END
`

func (q *Queries) IsBackupLocked(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, isBackupLocked)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const releaseBackupLock = `-- name: ReleaseBackupLock :execrows
UPDATE backup_lock SET running = false, started_at = NULL, owner_token = NULL
WHERE id = 1 AND running = true AND owner_token IS NOT DISTINCT FROM $1
`

func (q *Queries) ReleaseBackupLock(ctx context.Context, ownerToken uuid.NullUUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseBackupLock, ownerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseMaintenanceLockForTask = `-- name: ReleaseMaintenanceLockForTask :execrows
UPDATE backup_lock SET running = false, started_at = NULL, owner_token = NULL
WHERE id = 1 AND running = true AND owner_token IS NOT DISTINCT FROM $1
`

func (q *Queries) ReleaseMaintenanceLockForTask(ctx context.Context, ownerToken uuid.NullUUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseMaintenanceLockForTask, ownerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchMaintenanceLockForTask = `-- name: TouchMaintenanceLockForTask :execrows
UPDATE backup_lock SET started_at = NOW()
WHERE id = 1 AND running = true AND owner_token IS NOT DISTINCT FROM $1
`

func (q *Queries) TouchMaintenanceLockForTask(ctx context.Context, ownerToken uuid.NullUUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchMaintenanceLockForTask, ownerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
