// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup_lock.sql

package database

import (
	"context"
)

const acquireBackupLock = `-- name: AcquireBackupLock :execrows
UPDATE backup_lock SET running = true, started_at = NOW()
WHERE id = 1 AND (NOT running OR started_at <= NOW() - INTERVAL '30 minutes')
`

func (q *Queries) AcquireBackupLock(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireBackupLock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const isBackupLocked = `-- name: IsBackupLocked :one
SELECT CASE WHEN is_backup_running() THEN 1 ELSE 0 END
`

func (q *Queries) IsBackupLocked(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, isBackupLocked)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const releaseBackupLock = `-- name: ReleaseBackupLock :execrows
UPDATE backup_lock SET running = false, started_at = NULL WHERE id = 1 AND running = true
`

func (q *Queries) ReleaseBackupLock(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseBackupLock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchBackupLock = `-- name: TouchBackupLock :execrows
UPDATE backup_lock SET started_at = NOW() WHERE id = 1 AND running = true
`

func (q *Queries) TouchBackupLock(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchBackupLock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
