// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const acquireBatchOwnerForce = `-- name: AcquireBatchOwnerForce :execrows
INSERT INTO batch_owner (batch_id, owner_id, pid, acquired_at, last_heartbeat)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(batch_id) DO UPDATE SET
  owner_id = excluded.owner_id,
  pid = excluded.pid,
  acquired_at = CURRENT_TIMESTAMP,
  last_heartbeat = CURRENT_TIMESTAMP
`

type AcquireBatchOwnerForceParams struct {
	BatchID string
	OwnerID string
	Pid     int64
}

func (q *Queries) AcquireBatchOwnerForce(ctx context.Context, arg AcquireBatchOwnerForceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireBatchOwnerForce, arg.BatchID, arg.OwnerID, arg.Pid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cleanupCompletedBatches = `-- name: CleanupCompletedBatches :execrows
DELETE FROM batch_owner WHERE batch_id IN (
  SELECT b.batch_id FROM batch_owner b
  WHERE NOT EXISTS (
    SELECT 1 FROM task t WHERE t.batch_id = b.batch_id
      AND t.status IN ('pending', 'processing', 'waiting')
  )
)
`

func (q *Queries) CleanupCompletedBatches(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupCompletedBatches)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createBatch = `-- name: CreateBatch :execresult
INSERT OR IGNORE INTO batch (id, source) VALUES (?, ?)
`

type CreateBatchParams struct {
	ID     string
	Source string
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBatch, arg.ID, arg.Source)
}

const getBatchOwner = `-- name: GetBatchOwner :one
SELECT batch_id, owner_id, pid, acquired_at, last_heartbeat FROM batch_owner WHERE batch_id = ?
`

func (q *Queries) GetBatchOwner(ctx context.Context, batchID string) (BatchOwner, error) {
	row := q.db.QueryRowContext(ctx, getBatchOwner, batchID)
	var i BatchOwner
	err := row.Scan(
		&i.BatchID,
		&i.OwnerID,
		&i.Pid,
		&i.AcquiredAt,
		&i.LastHeartbeat,
	)
	return i, err
}

const getNextPendingTaskOfTypeForOwner = `-- name: GetNextPendingTaskOfTypeForOwner :one
SELECT id FROM task
WHERE status = 'pending' AND task_type = ?
  AND batch_id IN (SELECT batch_id FROM batch_owner WHERE owner_id = ?)
ORDER BY created_at LIMIT 1
`

type GetNextPendingTaskOfTypeForOwnerParams struct {
	TaskType string
	OwnerID  string
}

func (q *Queries) GetNextPendingTaskOfTypeForOwner(ctx context.Context, arg GetNextPendingTaskOfTypeForOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingTaskOfTypeForOwner, arg.TaskType, arg.OwnerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const heartbeatBatchOwner = `-- name: HeartbeatBatchOwner :execrows
UPDATE batch_owner SET last_heartbeat = CURRENT_TIMESTAMP WHERE owner_id = ?
`

func (q *Queries) HeartbeatBatchOwner(ctx context.Context, ownerID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatBatchOwner, ownerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseBatchOwner = `-- name: ReleaseBatchOwner :execrows
DELETE FROM batch_owner WHERE batch_id = ? AND owner_id = ?
`

type ReleaseBatchOwnerParams struct {
	BatchID string
	OwnerID string
}

func (q *Queries) ReleaseBatchOwner(ctx context.Context, arg ReleaseBatchOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseBatchOwner, arg.BatchID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetProcessingTasksByBatch = `-- name: ResetProcessingTasksByBatch :execrows
UPDATE task SET status = 'pending'
WHERE batch_id = ? AND status = 'processing'
`

func (q *Queries) ResetProcessingTasksByBatch(ctx context.Context, batchID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetProcessingTasksByBatch, batchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tryInsertBatchOwner = `-- name: TryInsertBatchOwner :execrows

INSERT INTO batch_owner (batch_id, owner_id, pid, acquired_at, last_heartbeat)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(batch_id) DO NOTHING
`

type TryInsertBatchOwnerParams struct {
	BatchID string
	OwnerID string
	Pid     int64
}

// Two-step acquire: try INSERT first, then UPDATE with stale check.
// The raw ON CONFLICT ... WHERE pattern has ? count issues with sqlc's parser.
func (q *Queries) TryInsertBatchOwner(ctx context.Context, arg TryInsertBatchOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tryInsertBatchOwner, arg.BatchID, arg.OwnerID, arg.Pid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateBatchOwnerIfStale = `-- name: UpdateBatchOwnerIfStale :execrows
UPDATE batch_owner SET
  owner_id = ?,
  pid = ?,
  acquired_at = CURRENT_TIMESTAMP,
  last_heartbeat = CURRENT_TIMESTAMP
WHERE batch_id = ? AND (last_heartbeat < ? OR owner_id = ?)
`

type UpdateBatchOwnerIfStaleParams struct {
	OwnerID       string
	Pid           int64
	BatchID       string
	LastHeartbeat time.Time
	OwnerID_2     string
}

func (q *Queries) UpdateBatchOwnerIfStale(ctx context.Context, arg UpdateBatchOwnerIfStaleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBatchOwnerIfStale,
		arg.OwnerID,
		arg.Pid,
		arg.BatchID,
		arg.LastHeartbeat,
		arg.OwnerID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
