// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const acquireBatchOwnerForce = `-- name: AcquireBatchOwnerForce :execrows
INSERT INTO batch_owner (batch_id, owner_id, pid, acquired_at, last_heartbeat)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(batch_id) DO UPDATE SET
  owner_id = excluded.owner_id,
  pid = excluded.pid,
  acquired_at = CURRENT_TIMESTAMP,
  last_heartbeat = CURRENT_TIMESTAMP
`

type AcquireBatchOwnerForceParams struct {
	BatchID string
	OwnerID string
	Pid     int64
}

func (q *Queries) AcquireBatchOwnerForce(ctx context.Context, arg AcquireBatchOwnerForceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireBatchOwnerForce, arg.BatchID, arg.OwnerID, arg.Pid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cleanupCompletedBatches = `-- name: CleanupCompletedBatches :execrows
DELETE FROM batch_owner WHERE batch_id IN (
  SELECT b.batch_id FROM batch_owner b
  WHERE NOT EXISTS (
    SELECT 1 FROM task t WHERE t.batch_id = b.batch_id
      AND t.status IN ('pending', 'processing', 'waiting')
  )
)
`

func (q *Queries) CleanupCompletedBatches(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupCompletedBatches)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countLiveBatches = `-- name: CountLiveBatches :one
SELECT COUNT(*) FROM batch_owner
WHERE last_heartbeat > datetime('now', '-15 seconds')
`

func (q *Queries) CountLiveBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveBatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueuedBatches = `-- name: CountQueuedBatches :one
SELECT COUNT(*) FROM batch WHERE status = 'queued'
`

func (q *Queries) CountQueuedBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedBatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatch = `-- name: CreateBatch :execresult
INSERT OR IGNORE INTO batch (id, source, status) VALUES (?, ?, ?)
`

type CreateBatchParams struct {
	ID     string
	Source string
	Status string
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBatch, arg.ID, arg.Source, arg.Status)
}

const deleteBatchOwnerByBatchID = `-- name: DeleteBatchOwnerByBatchID :execrows
DELETE FROM batch_owner WHERE batch_id = ?
`

func (q *Queries) DeleteBatchOwnerByBatchID(ctx context.Context, batchID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBatchOwnerByBatchID, batchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBatch = `-- name: GetBatch :one
SELECT id, source, created_at, status FROM batch WHERE id = ?
`

func (q *Queries) GetBatch(ctx context.Context, id string) (Batch, error) {
	row := q.db.QueryRowContext(ctx, getBatch, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getBatchOwner = `-- name: GetBatchOwner :one
SELECT batch_id, owner_id, pid, acquired_at, last_heartbeat FROM batch_owner WHERE batch_id = ?
`

func (q *Queries) GetBatchOwner(ctx context.Context, batchID string) (BatchOwner, error) {
	row := q.db.QueryRowContext(ctx, getBatchOwner, batchID)
	var i BatchOwner
	err := row.Scan(
		&i.BatchID,
		&i.OwnerID,
		&i.Pid,
		&i.AcquiredAt,
		&i.LastHeartbeat,
	)
	return i, err
}

const getNextPendingTaskOfTypeForOwner = `-- name: GetNextPendingTaskOfTypeForOwner :one
SELECT id FROM task
WHERE status = 'pending' AND task_type = ?
  AND batch_id IN (SELECT batch_id FROM batch_owner WHERE owner_id = ?)
ORDER BY created_at LIMIT 1
`

type GetNextPendingTaskOfTypeForOwnerParams struct {
	TaskType string
	OwnerID  string
}

func (q *Queries) GetNextPendingTaskOfTypeForOwner(ctx context.Context, arg GetNextPendingTaskOfTypeForOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingTaskOfTypeForOwner, arg.TaskType, arg.OwnerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getNextQueuedBatch = `-- name: GetNextQueuedBatch :one
SELECT id, source, created_at, status FROM batch WHERE status = 'queued' ORDER BY created_at LIMIT 1
`

func (q *Queries) GetNextQueuedBatch(ctx context.Context) (Batch, error) {
	row := q.db.QueryRowContext(ctx, getNextQueuedBatch)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const heartbeatBatchOwner = `-- name: HeartbeatBatchOwner :execrows
UPDATE batch_owner SET last_heartbeat = CURRENT_TIMESTAMP WHERE owner_id = ?
`

func (q *Queries) HeartbeatBatchOwner(ctx context.Context, ownerID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatBatchOwner, ownerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listBatchOverviews = `-- name: ListBatchOverviews :many
SELECT
    b.id AS batch_id,
    b.source,
    b.created_at AS batch_created_at,
    b.status AS batch_status,
    COUNT(t.id) AS total,
    COALESCE(SUM(CASE WHEN t.status = 'waiting'   THEN 1 ELSE 0 END), 0) AS waiting,
    COALESCE(SUM(CASE WHEN t.status = 'pending'   THEN 1 ELSE 0 END), 0) AS pending,
    COALESCE(SUM(CASE WHEN t.status = 'processing' THEN 1 ELSE 0 END), 0) AS processing,
    COALESCE(SUM(CASE WHEN t.status = 'completed' THEN 1 ELSE 0 END), 0) AS completed,
    COALESCE(SUM(CASE WHEN t.status = 'failed'    THEN 1 ELSE 0 END), 0) AS failed,
    COALESCE(SUM(CASE WHEN t.status = 'cancelled' THEN 1 ELSE 0 END), 0) AS cancelled,
    COALESCE(SUM(CASE WHEN t.status = 'discarded' THEN 1 ELSE 0 END), 0) AS discarded,
    MIN(t.started_at) AS first_started_at,
    MAX(t.completed_at) AS last_completed_at,
    bo.last_heartbeat AS owner_last_heartbeat,
    bo.pid AS owner_pid
FROM batch b
LEFT JOIN task t ON t.batch_id = b.id
LEFT JOIN batch_owner bo ON bo.batch_id = b.id
GROUP BY b.id
ORDER BY b.created_at DESC
LIMIT ? OFFSET ?
`

type ListBatchOverviewsParams struct {
	Limit  int64
	Offset int64
}

type ListBatchOverviewsRow struct {
	BatchID            string
	Source             string
	BatchCreatedAt     sql.NullTime
	BatchStatus        string
	Total              int64
	Waiting            interface{}
	Pending            interface{}
	Processing         interface{}
	Completed          interface{}
	Failed             interface{}
	Cancelled          interface{}
	Discarded          interface{}
	FirstStartedAt     interface{}
	LastCompletedAt    interface{}
	OwnerLastHeartbeat sql.NullTime
	OwnerPid           sql.NullInt64
}

func (q *Queries) ListBatchOverviews(ctx context.Context, arg ListBatchOverviewsParams) ([]ListBatchOverviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBatchOverviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchOverviewsRow
	for rows.Next() {
		var i ListBatchOverviewsRow
		if err := rows.Scan(
			&i.BatchID,
			&i.Source,
			&i.BatchCreatedAt,
			&i.BatchStatus,
			&i.Total,
			&i.Waiting,
			&i.Pending,
			&i.Processing,
			&i.Completed,
			&i.Failed,
			&i.Cancelled,
			&i.Discarded,
			&i.FirstStartedAt,
			&i.LastCompletedAt,
			&i.OwnerLastHeartbeat,
			&i.OwnerPid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleBatchOwners = `-- name: ListStaleBatchOwners :many
SELECT bo.batch_id, bo.owner_id, bo.pid FROM batch_owner bo
WHERE bo.last_heartbeat < datetime('now', '-15 seconds')
AND EXISTS (SELECT 1 FROM task t
            WHERE t.batch_id = bo.batch_id
            AND t.status IN ('pending', 'processing', 'waiting'))
`

type ListStaleBatchOwnersRow struct {
	BatchID string
	OwnerID string
	Pid     int64
}

func (q *Queries) ListStaleBatchOwners(ctx context.Context) ([]ListStaleBatchOwnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleBatchOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleBatchOwnersRow
	for rows.Next() {
		var i ListStaleBatchOwnersRow
		if err := rows.Scan(&i.BatchID, &i.OwnerID, &i.Pid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarantineProcessingTasksByBatch = `-- name: QuarantineProcessingTasksByBatch :execrows
UPDATE task SET
    status = 'failed',
    error = 'Max retries exceeded (' || attempts || ')',
    completed_at = CURRENT_TIMESTAMP
WHERE batch_id = ? AND status = 'processing' AND attempts >= ?
`

type QuarantineProcessingTasksByBatchParams struct {
	BatchID  sql.NullString
	Attempts int64
}

func (q *Queries) QuarantineProcessingTasksByBatch(ctx context.Context, arg QuarantineProcessingTasksByBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, quarantineProcessingTasksByBatch, arg.BatchID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseBatchOwner = `-- name: ReleaseBatchOwner :execrows
DELETE FROM batch_owner WHERE batch_id = ? AND owner_id = ?
`

type ReleaseBatchOwnerParams struct {
	BatchID string
	OwnerID string
}

func (q *Queries) ReleaseBatchOwner(ctx context.Context, arg ReleaseBatchOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseBatchOwner, arg.BatchID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueBatch = `-- name: RequeueBatch :exec
UPDATE batch SET status = 'queued' WHERE id = ?
`

func (q *Queries) RequeueBatch(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, requeueBatch, id)
	return err
}

const resetProcessingTasksByBatch = `-- name: ResetProcessingTasksByBatch :execrows
UPDATE task SET
    status = 'pending',
    attempts = attempts + 1
WHERE batch_id = ? AND status = 'processing' AND attempts < ?
`

type ResetProcessingTasksByBatchParams struct {
	BatchID  sql.NullString
	Attempts int64
}

func (q *Queries) ResetProcessingTasksByBatch(ctx context.Context, arg ResetProcessingTasksByBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetProcessingTasksByBatch, arg.BatchID, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setBatchCancelled = `-- name: SetBatchCancelled :exec
UPDATE batch SET status = 'cancelled' WHERE id = ?
`

func (q *Queries) SetBatchCancelled(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setBatchCancelled, id)
	return err
}

const setBatchCompleted = `-- name: SetBatchCompleted :exec
UPDATE batch SET status = 'completed' WHERE id = ?
`

func (q *Queries) SetBatchCompleted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setBatchCompleted, id)
	return err
}

const setBatchFailed = `-- name: SetBatchFailed :exec
UPDATE batch SET status = 'failed' WHERE id = ?
`

func (q *Queries) SetBatchFailed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setBatchFailed, id)
	return err
}

const setBatchProcessing = `-- name: SetBatchProcessing :exec
UPDATE batch SET status = 'processing' WHERE id = ?
`

func (q *Queries) SetBatchProcessing(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setBatchProcessing, id)
	return err
}

const tryInsertBatchOwner = `-- name: TryInsertBatchOwner :execrows

INSERT INTO batch_owner (batch_id, owner_id, pid, acquired_at, last_heartbeat)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(batch_id) DO NOTHING
`

type TryInsertBatchOwnerParams struct {
	BatchID string
	OwnerID string
	Pid     int64
}

// Two-step acquire: try INSERT first, then UPDATE with stale check.
// The raw ON CONFLICT ... WHERE pattern has ? count issues with sqlc's parser.
func (q *Queries) TryInsertBatchOwner(ctx context.Context, arg TryInsertBatchOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tryInsertBatchOwner, arg.BatchID, arg.OwnerID, arg.Pid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateBatchOwnerIfStale = `-- name: UpdateBatchOwnerIfStale :execrows
UPDATE batch_owner SET
  owner_id = ?,
  pid = ?,
  acquired_at = CURRENT_TIMESTAMP,
  last_heartbeat = CURRENT_TIMESTAMP
WHERE batch_id = ? AND (last_heartbeat < ? OR owner_id = ?)
`

type UpdateBatchOwnerIfStaleParams struct {
	OwnerID       string
	Pid           int64
	BatchID       string
	LastHeartbeat time.Time
	OwnerID_2     string
}

func (q *Queries) UpdateBatchOwnerIfStale(ctx context.Context, arg UpdateBatchOwnerIfStaleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBatchOwnerIfStale,
		arg.OwnerID,
		arg.Pid,
		arg.BatchID,
		arg.LastHeartbeat,
		arg.OwnerID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
