// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_tag.sql

package database

import (
	"context"
	"database/sql"
)

const addDocumentTag = `-- name: AddDocumentTag :exec
INSERT INTO document_tag (document_id, tag_id) VALUES (?, ?)
`

type AddDocumentTagParams struct {
	DocumentID int64
	TagID      int64
}

func (q *Queries) AddDocumentTag(ctx context.Context, arg AddDocumentTagParams) error {
	_, err := q.db.ExecContext(ctx, addDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const clearDocumentTags = `-- name: ClearDocumentTags :exec
DELETE FROM document_tag WHERE document_id = ?
`

func (q *Queries) ClearDocumentTags(ctx context.Context, documentID int64) error {
	_, err := q.db.ExecContext(ctx, clearDocumentTags, documentID)
	return err
}

const getDocumentTags = `-- name: GetDocumentTags :many
SELECT t.id, t.name, t.created_at FROM tag t
JOIN document_tag dt ON t.id = dt.tag_id
WHERE dt.document_id = ?
`

func (q *Queries) GetDocumentTags(ctx context.Context, documentID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagDocuments = `-- name: GetTagDocuments :many
SELECT d.id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size,
       d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path
FROM document d
JOIN document_tag dt ON d.id = dt.document_id
WHERE dt.tag_id = ?
`

type GetTagDocumentsRow struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID sql.NullInt64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) GetTagDocuments(ctx context.Context, tagID int64) ([]GetTagDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagDocuments, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagDocumentsRow
	for rows.Next() {
		var i GetTagDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentTag = `-- name: RemoveDocumentTag :exec
DELETE FROM document_tag WHERE document_id = ? AND tag_id = ?
`

type RemoveDocumentTagParams struct {
	DocumentID int64
	TagID      int64
}

func (q *Queries) RemoveDocumentTag(ctx context.Context, arg RemoveDocumentTagParams) error {
	_, err := q.db.ExecContext(ctx, removeDocumentTag, arg.DocumentID, arg.TagID)
	return err
}
