// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package database

import (
	"context"
	"database/sql"
)

const countAllDocuments = `-- name: CountAllDocuments :one
SELECT COUNT(*) FROM document
`

func (q *Queries) CountAllDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO document (
    document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
    char_count, language, original_path, storage_path, text_content
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id
`

type CreateDocumentParams struct {
	DocumentID     string
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int32
	WordCount      int32
	CharCount      int32
	Language       string
	OriginalPath   string
	StoragePath    string
	TextContent    sql.NullString
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.DocumentID,
		arg.Title,
		arg.Md5Checksum,
		arg.Sha512Checksum,
		arg.MimeType,
		arg.FileSize,
		arg.PageCount,
		arg.WordCount,
		arg.CharCount,
		arg.Language,
		arg.OriginalPath,
		arg.StoragePath,
		arg.TextContent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM document WHERE document_id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, documentID)
	return err
}

const deleteDocumentById = `-- name: DeleteDocumentById :exec
DELETE FROM document WHERE id = $1
`

func (q *Queries) DeleteDocumentById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentById, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path, text_content
FROM document WHERE document_id = $1
`

func (q *Queries) GetDocument(ctx context.Context, documentID string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, documentID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
	)
	return i, err
}

const getDocumentById = `-- name: GetDocumentById :one
SELECT id, document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path, text_content
FROM document WHERE id = $1
`

func (q *Queries) GetDocumentById(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentById, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
	)
	return i, err
}

const getDocumentByMD5Checksum = `-- name: GetDocumentByMD5Checksum :many
SELECT id, document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document WHERE md5_checksum = $1
`

type GetDocumentByMD5ChecksumRow struct {
	ID             int64
	DocumentID     string
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int32
	WordCount      int32
	CharCount      int32
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) GetDocumentByMD5Checksum(ctx context.Context, md5Checksum string) ([]GetDocumentByMD5ChecksumRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentByMD5Checksum, md5Checksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentByMD5ChecksumRow
	for rows.Next() {
		var i GetDocumentByMD5ChecksumRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.PageCount,
			&i.WordCount,
			&i.CharCount,
			&i.Language,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentBySHA512Checksum = `-- name: GetDocumentBySHA512Checksum :one
SELECT id, document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document WHERE sha512_checksum = $1
`

type GetDocumentBySHA512ChecksumRow struct {
	ID             int64
	DocumentID     string
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int32
	WordCount      int32
	CharCount      int32
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) GetDocumentBySHA512Checksum(ctx context.Context, sha512Checksum string) (GetDocumentBySHA512ChecksumRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySHA512Checksum, sha512Checksum)
	var i GetDocumentBySHA512ChecksumRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
	)
	return i, err
}

const getDocumentWithDetails = `-- name: GetDocumentWithDetails :one
SELECT d.id, d.document_id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size,
       d.page_count, d.word_count, d.char_count, d.language, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path, d.text_content, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.document_id = $1
`

type GetDocumentWithDetailsRow struct {
	ID               int64
	DocumentID       string
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	PageCount        int32
	WordCount        int32
	CharCount        int32
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithDetails(ctx context.Context, documentID string) (GetDocumentWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithDetails, documentID)
	var i GetDocumentWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
		&i.DocumentTypeName,
	)
	return i, err
}

const getDocumentWithDetailsById = `-- name: GetDocumentWithDetailsById :one
SELECT d.id, d.document_id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size,
       d.page_count, d.word_count, d.char_count, d.language, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path, d.text_content, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.id = $1
`

type GetDocumentWithDetailsByIdRow struct {
	ID               int64
	DocumentID       string
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	PageCount        int32
	WordCount        int32
	CharCount        int32
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithDetailsById(ctx context.Context, id int64) (GetDocumentWithDetailsByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithDetailsById, id)
	var i GetDocumentWithDetailsByIdRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
		&i.DocumentTypeName,
	)
	return i, err
}

const getDocumentWithText = `-- name: GetDocumentWithText :one
SELECT d.id, d.document_id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size,
       d.page_count, d.word_count, d.char_count, d.language, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path, d.text_content, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.document_id = $1
`

type GetDocumentWithTextRow struct {
	ID               int64
	DocumentID       string
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	PageCount        int32
	WordCount        int32
	CharCount        int32
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithText(ctx context.Context, documentID string) (GetDocumentWithTextRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithText, documentID)
	var i GetDocumentWithTextRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
		&i.DocumentTypeName,
	)
	return i, err
}

const getDocumentWithTextById = `-- name: GetDocumentWithTextById :one
SELECT d.id, d.document_id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size,
       d.page_count, d.word_count, d.char_count, d.language, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path, d.text_content, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.id = $1
`

type GetDocumentWithTextByIdRow struct {
	ID               int64
	DocumentID       string
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	PageCount        int32
	WordCount        int32
	CharCount        int32
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithTextById(ctx context.Context, id int64) (GetDocumentWithTextByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithTextById, id)
	var i GetDocumentWithTextByIdRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
		&i.DocumentTypeName,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32
	Offset int32
}

type ListDocumentsRow struct {
	ID             int64
	DocumentID     string
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int32
	WordCount      int32
	CharCount      int32
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.PageCount,
			&i.WordCount,
			&i.CharCount,
			&i.Language,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsByTitle = `-- name: SearchDocumentsByTitle :many
SELECT id, document_id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document
WHERE title LIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchDocumentsByTitleParams struct {
	Title  string
	Limit  int32
	Offset int32
}

type SearchDocumentsByTitleRow struct {
	ID             int64
	DocumentID     string
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int32
	WordCount      int32
	CharCount      int32
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) SearchDocumentsByTitle(ctx context.Context, arg SearchDocumentsByTitleParams) ([]SearchDocumentsByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentsByTitle, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsByTitleRow
	for rows.Next() {
		var i SearchDocumentsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.PageCount,
			&i.WordCount,
			&i.CharCount,
			&i.Language,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDocumentFileSizes = `-- name: SumDocumentFileSizes :one
SELECT CAST(COALESCE(SUM(file_size), 0) AS BIGINT) AS total_bytes FROM document
`

func (q *Queries) SumDocumentFileSizes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumDocumentFileSizes)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const updateDocumentEditable = `-- name: UpdateDocumentEditable :exec
UPDATE document SET
    title = $1,
    document_type_id = $2,
    language = $3,
    text_content = $4,
    modified_at = CURRENT_TIMESTAMP
WHERE document_id = $5
`

type UpdateDocumentEditableParams struct {
	Title          string
	DocumentTypeID int64
	Language       string
	TextContent    sql.NullString
	DocumentID     string
}

func (q *Queries) UpdateDocumentEditable(ctx context.Context, arg UpdateDocumentEditableParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentEditable,
		arg.Title,
		arg.DocumentTypeID,
		arg.Language,
		arg.TextContent,
		arg.DocumentID,
	)
	return err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :exec
UPDATE document SET
    title = $1,
    document_type_id = $2,
    language = $3,
    modified_at = CURRENT_TIMESTAMP
WHERE document_id = $4
`

type UpdateDocumentMetadataParams struct {
	Title          string
	DocumentTypeID int64
	Language       string
	DocumentID     string
}

func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentMetadata,
		arg.Title,
		arg.DocumentTypeID,
		arg.Language,
		arg.DocumentID,
	)
	return err
}

const updateDocumentMetadataById = `-- name: UpdateDocumentMetadataById :exec
UPDATE document SET
    title = $1,
    document_type_id = $2,
    language = $3,
    modified_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdateDocumentMetadataByIdParams struct {
	Title          string
	DocumentTypeID int64
	Language       string
	ID             int64
}

func (q *Queries) UpdateDocumentMetadataById(ctx context.Context, arg UpdateDocumentMetadataByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentMetadataById,
		arg.Title,
		arg.DocumentTypeID,
		arg.Language,
		arg.ID,
	)
	return err
}

const updateDocumentPaths = `-- name: UpdateDocumentPaths :exec
UPDATE document SET
    original_path = $1,
    storage_path = $2,
    modified_at = CURRENT_TIMESTAMP
WHERE document_id = $3
`

type UpdateDocumentPathsParams struct {
	OriginalPath string
	StoragePath  string
	DocumentID   string
}

func (q *Queries) UpdateDocumentPaths(ctx context.Context, arg UpdateDocumentPathsParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentPaths, arg.OriginalPath, arg.StoragePath, arg.DocumentID)
	return err
}

const updateDocumentPathsById = `-- name: UpdateDocumentPathsById :exec
UPDATE document SET
    original_path = $1,
    storage_path = $2,
    modified_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateDocumentPathsByIdParams struct {
	OriginalPath string
	StoragePath  string
	ID           int64
}

func (q *Queries) UpdateDocumentPathsById(ctx context.Context, arg UpdateDocumentPathsByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentPathsById, arg.OriginalPath, arg.StoragePath, arg.ID)
	return err
}
