// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package database

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :execresult
INSERT INTO document (
    title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
    char_count, language, original_path, storage_path, text_content
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDocumentParams struct {
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int64
	WordCount      int64
	CharCount      int64
	Language       string
	OriginalPath   string
	StoragePath    string
	TextContent    sql.NullString
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDocument,
		arg.Title,
		arg.Md5Checksum,
		arg.Sha512Checksum,
		arg.MimeType,
		arg.FileSize,
		arg.PageCount,
		arg.WordCount,
		arg.CharCount,
		arg.Language,
		arg.OriginalPath,
		arg.StoragePath,
		arg.TextContent,
	)
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM document WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path, text_content
FROM document WHERE id = ?
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
	)
	return i, err
}

const getDocumentByMD5Checksum = `-- name: GetDocumentByMD5Checksum :many
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count, char_count,
       language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document WHERE md5_checksum = ?
`

type GetDocumentByMD5ChecksumRow struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int64
	WordCount      int64
	CharCount      int64
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) GetDocumentByMD5Checksum(ctx context.Context, md5Checksum string) ([]GetDocumentByMD5ChecksumRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentByMD5Checksum, md5Checksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentByMD5ChecksumRow
	for rows.Next() {
		var i GetDocumentByMD5ChecksumRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.PageCount,
			&i.WordCount,
			&i.CharCount,
			&i.Language,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentBySHA512Checksum = `-- name: GetDocumentBySHA512Checksum :one
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count, char_count,
       language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document WHERE sha512_checksum = ?
`

type GetDocumentBySHA512ChecksumRow struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int64
	WordCount      int64
	CharCount      int64
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) GetDocumentBySHA512Checksum(ctx context.Context, sha512Checksum string) (GetDocumentBySHA512ChecksumRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySHA512Checksum, sha512Checksum)
	var i GetDocumentBySHA512ChecksumRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
	)
	return i, err
}

const getDocumentWithDetails = `-- name: GetDocumentWithDetails :one
SELECT d.id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size, d.page_count, d.word_count,
       d.char_count, d.language, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path,
       d.text_content, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.id = ?
`

type GetDocumentWithDetailsRow struct {
	ID               int64
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	PageCount        int64
	WordCount        int64
	CharCount        int64
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithDetails(ctx context.Context, id int64) (GetDocumentWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithDetails, id)
	var i GetDocumentWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
		&i.DocumentTypeName,
	)
	return i, err
}

const getDocumentWithText = `-- name: GetDocumentWithText :one
SELECT d.id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size, d.page_count, d.word_count,
       d.char_count, d.language, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path,
       d.text_content, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.id = ?
`

type GetDocumentWithTextRow struct {
	ID               int64
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	PageCount        int64
	WordCount        int64
	CharCount        int64
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithText(ctx context.Context, id int64) (GetDocumentWithTextRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithText, id)
	var i GetDocumentWithTextRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.PageCount,
		&i.WordCount,
		&i.CharCount,
		&i.Language,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.TextContent,
		&i.DocumentTypeName,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count,
       char_count, language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	Limit  int64
	Offset int64
}

type ListDocumentsRow struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int64
	WordCount      int64
	CharCount      int64
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.PageCount,
			&i.WordCount,
			&i.CharCount,
			&i.Language,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsByTitle = `-- name: SearchDocumentsByTitle :many
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, page_count, word_count, char_count,
       language, created_at, modified_at, document_type_id, original_path, storage_path
FROM document
WHERE title LIKE ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchDocumentsByTitleParams struct {
	Title  string
	Limit  int64
	Offset int64
}

type SearchDocumentsByTitleRow struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int64
	WordCount      int64
	CharCount      int64
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) SearchDocumentsByTitle(ctx context.Context, arg SearchDocumentsByTitleParams) ([]SearchDocumentsByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentsByTitle, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentsByTitleRow
	for rows.Next() {
		var i SearchDocumentsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.PageCount,
			&i.WordCount,
			&i.CharCount,
			&i.Language,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDocumentFileSizes = `-- name: SumDocumentFileSizes :one
SELECT CAST(COALESCE(SUM(file_size), 0) AS INTEGER) AS total_bytes FROM document
`

func (q *Queries) SumDocumentFileSizes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumDocumentFileSizes)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :exec
UPDATE document SET
    title = ?,
    document_type_id = ?,
    language = ?,
    modified_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDocumentMetadataParams struct {
	Title          string
	DocumentTypeID int64
	Language       string
	ID             int64
}

func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentMetadata,
		arg.Title,
		arg.DocumentTypeID,
		arg.Language,
		arg.ID,
	)
	return err
}

const updateDocumentPaths = `-- name: UpdateDocumentPaths :exec
UPDATE document SET
    original_path = ?,
    storage_path = ?,
    modified_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDocumentPathsParams struct {
	OriginalPath string
	StoragePath  string
	ID           int64
}

func (q *Queries) UpdateDocumentPaths(ctx context.Context, arg UpdateDocumentPathsParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentPaths, arg.OriginalPath, arg.StoragePath, arg.ID)
	return err
}
