// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package database

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :execresult
INSERT INTO document (
    title, md5_checksum, sha512_checksum, mime_type, file_size, original_path, storage_path
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDocumentParams struct {
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDocument,
		arg.Title,
		arg.Md5Checksum,
		arg.Sha512Checksum,
		arg.MimeType,
		arg.FileSize,
		arg.OriginalPath,
		arg.StoragePath,
	)
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM document WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, created_at, modified_at, document_type_id, original_path, storage_path FROM document WHERE id = ?
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
	)
	return i, err
}

const getDocumentByMD5Checksum = `-- name: GetDocumentByMD5Checksum :many
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, created_at, modified_at, document_type_id, original_path, storage_path FROM document WHERE md5_checksum = ?
`

func (q *Queries) GetDocumentByMD5Checksum(ctx context.Context, md5Checksum string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentByMD5Checksum, md5Checksum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentBySHA512Checksum = `-- name: GetDocumentBySHA512Checksum :one
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, created_at, modified_at, document_type_id, original_path, storage_path FROM document WHERE sha512_checksum = ?
`

func (q *Queries) GetDocumentBySHA512Checksum(ctx context.Context, sha512Checksum string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySHA512Checksum, sha512Checksum)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
	)
	return i, err
}

const getDocumentWithDetails = `-- name: GetDocumentWithDetails :one
SELECT d.id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path, dt.name as document_type_name
FROM document d
LEFT JOIN document_type dt ON d.document_type_id = dt.id
WHERE d.id = ?
`

type GetDocumentWithDetailsRow struct {
	ID               int64
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	MimeType         string
	FileSize         int64
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   sql.NullInt64
	OriginalPath     string
	StoragePath      string
	DocumentTypeName sql.NullString
}

func (q *Queries) GetDocumentWithDetails(ctx context.Context, id int64) (GetDocumentWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentWithDetails, id)
	var i GetDocumentWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Md5Checksum,
		&i.Sha512Checksum,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DocumentTypeID,
		&i.OriginalPath,
		&i.StoragePath,
		&i.DocumentTypeName,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, created_at, modified_at, document_type_id, original_path, storage_path FROM document ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsByTitle = `-- name: SearchDocumentsByTitle :many
SELECT id, title, md5_checksum, sha512_checksum, mime_type, file_size, created_at, modified_at, document_type_id, original_path, storage_path FROM document
WHERE title LIKE ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchDocumentsByTitleParams struct {
	Title  string
	Limit  int64
	Offset int64
}

func (q *Queries) SearchDocumentsByTitle(ctx context.Context, arg SearchDocumentsByTitleParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentsByTitle, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentPaths = `-- name: UpdateDocumentPaths :exec
UPDATE document SET
    original_path = ?,
    storage_path = ?,
    modified_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDocumentPathsParams struct {
	OriginalPath string
	StoragePath  string
	ID           int64
}

func (q *Queries) UpdateDocumentPaths(ctx context.Context, arg UpdateDocumentPathsParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentPaths, arg.OriginalPath, arg.StoragePath, arg.ID)
	return err
}
