// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_people.sql

package database

import (
	"context"
	"database/sql"
)

const addDocumentPeople = `-- name: AddDocumentPeople :exec
INSERT INTO document_people (document_id, people_id, people_type_id)
VALUES ($1, $2, $3)
ON CONFLICT (document_id, people_id, people_type_id) DO NOTHING
`

type AddDocumentPeopleParams struct {
	DocumentID   int64
	PeopleID     int64
	PeopleTypeID int64
}

func (q *Queries) AddDocumentPeople(ctx context.Context, arg AddDocumentPeopleParams) error {
	_, err := q.db.ExecContext(ctx, addDocumentPeople, arg.DocumentID, arg.PeopleID, arg.PeopleTypeID)
	return err
}

const clearDocumentPeople = `-- name: ClearDocumentPeople :exec
DELETE FROM document_people WHERE document_id = $1
`

func (q *Queries) ClearDocumentPeople(ctx context.Context, documentID int64) error {
	_, err := q.db.ExecContext(ctx, clearDocumentPeople, documentID)
	return err
}

const getDocumentPeople = `-- name: GetDocumentPeople :many
SELECT p.id, p.name, p.name_native, p.normalized_name, p.created_at, dp.people_type_id FROM people p
JOIN document_people dp ON p.id = dp.people_id
WHERE dp.document_id = $1
`

type GetDocumentPeopleRow struct {
	ID             int64
	Name           string
	NameNative     sql.NullString
	NormalizedName string
	CreatedAt      sql.NullTime
	PeopleTypeID   int64
}

func (q *Queries) GetDocumentPeople(ctx context.Context, documentID int64) ([]GetDocumentPeopleRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentPeople, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentPeopleRow
	for rows.Next() {
		var i GetDocumentPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.NormalizedName,
			&i.CreatedAt,
			&i.PeopleTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentPeopleWithType = `-- name: GetDocumentPeopleWithType :many
SELECT p.id, p.name, p.name_native, p.created_at AS people_created_at,
       pt.id AS people_type_id, pt.name AS people_type_name, pt.description AS people_type_description
FROM people p
JOIN document_people dp ON p.id = dp.people_id
JOIN people_type pt ON dp.people_type_id = pt.id
WHERE dp.document_id = $1
`

type GetDocumentPeopleWithTypeRow struct {
	ID                    int64
	Name                  string
	NameNative            sql.NullString
	PeopleCreatedAt       sql.NullTime
	PeopleTypeID          int64
	PeopleTypeName        string
	PeopleTypeDescription string
}

func (q *Queries) GetDocumentPeopleWithType(ctx context.Context, documentID int64) ([]GetDocumentPeopleWithTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentPeopleWithType, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentPeopleWithTypeRow
	for rows.Next() {
		var i GetDocumentPeopleWithTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.PeopleCreatedAt,
			&i.PeopleTypeID,
			&i.PeopleTypeName,
			&i.PeopleTypeDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeopleDocuments = `-- name: GetPeopleDocuments :many
SELECT d.id, d.title, d.md5_checksum, d.sha512_checksum, d.original_type, d.file_size,
       d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path
FROM document d
JOIN document_people dp ON d.id = dp.document_id
WHERE dp.people_id = $1
`

type GetPeopleDocumentsRow struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	OriginalType   string
	FileSize       int64
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
}

func (q *Queries) GetPeopleDocuments(ctx context.Context, peopleID int64) ([]GetPeopleDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPeopleDocuments, peopleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPeopleDocumentsRow
	for rows.Next() {
		var i GetPeopleDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.OriginalType,
			&i.FileSize,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentPeople = `-- name: RemoveDocumentPeople :exec
DELETE FROM document_people WHERE document_id = $1 AND people_id = $2 AND people_type_id = $3
`

type RemoveDocumentPeopleParams struct {
	DocumentID   int64
	PeopleID     int64
	PeopleTypeID int64
}

func (q *Queries) RemoveDocumentPeople(ctx context.Context, arg RemoveDocumentPeopleParams) error {
	_, err := q.db.ExecContext(ctx, removeDocumentPeople, arg.DocumentID, arg.PeopleID, arg.PeopleTypeID)
	return err
}
