// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_type.sql

package database

import (
	"context"
	"database/sql"
)

const createDocumentType = `-- name: CreateDocumentType :execresult
INSERT INTO document_type (name) VALUES ($1)
`

func (q *Queries) CreateDocumentType(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDocumentType, name)
}

const createDocumentTypeFull = `-- name: CreateDocumentTypeFull :execresult
INSERT INTO document_type (name, description) VALUES ($1, $2)
`

type CreateDocumentTypeFullParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateDocumentTypeFull(ctx context.Context, arg CreateDocumentTypeFullParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDocumentTypeFull, arg.Name, arg.Description)
}

const deleteDocumentType = `-- name: DeleteDocumentType :exec
DELETE FROM document_type WHERE id = $1
`

func (q *Queries) DeleteDocumentType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentType, id)
	return err
}

const getDocumentType = `-- name: GetDocumentType :one
SELECT id, name, description, created_at FROM document_type WHERE id = $1
`

func (q *Queries) GetDocumentType(ctx context.Context, id int64) (DocumentType, error) {
	row := q.db.QueryRowContext(ctx, getDocumentType, id)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentTypeByName = `-- name: GetDocumentTypeByName :one
SELECT id, name, description, created_at FROM document_type WHERE name = $1
`

func (q *Queries) GetDocumentTypeByName(ctx context.Context, name string) (DocumentType, error) {
	row := q.db.QueryRowContext(ctx, getDocumentTypeByName, name)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDocumentTypes = `-- name: ListAllDocumentTypes :many
SELECT id, name, description, created_at FROM document_type ORDER BY created_at DESC
`

func (q *Queries) ListAllDocumentTypes(ctx context.Context) ([]DocumentType, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocumentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentType
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDocumentTypesNames = `-- name: ListAllDocumentTypesNames :many
SELECT name FROM document_type ORDER BY created_at DESC
`

func (q *Queries) ListAllDocumentTypesNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocumentTypesNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDocumentTypesWithDocumentCount = `-- name: ListAllDocumentTypesWithDocumentCount :many
SELECT dt.id, dt.name, dt.description, dt.created_at, COUNT(d.id) AS document_count
FROM document_type dt
LEFT JOIN document d ON dt.id = d.document_type_id
GROUP BY dt.id
ORDER BY dt.created_at DESC
`

type ListAllDocumentTypesWithDocumentCountRow struct {
	ID            int64
	Name          string
	Description   string
	CreatedAt     sql.NullTime
	DocumentCount int64
}

func (q *Queries) ListAllDocumentTypesWithDocumentCount(ctx context.Context) ([]ListAllDocumentTypesWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocumentTypesWithDocumentCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDocumentTypesWithDocumentCountRow
	for rows.Next() {
		var i ListAllDocumentTypesWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTypes = `-- name: ListDocumentTypes :many
SELECT id, name, description, created_at FROM document_type ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListDocumentTypesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDocumentTypes(ctx context.Context, arg ListDocumentTypesParams) ([]DocumentType, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentType
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTypesWithDocumentCount = `-- name: ListDocumentTypesWithDocumentCount :many
SELECT dt.id, dt.name, dt.description, dt.created_at, COUNT(d.id) AS document_count
FROM document_type dt
LEFT JOIN document d ON dt.id = d.document_type_id
GROUP BY dt.id
ORDER BY dt.created_at DESC LIMIT $1 OFFSET $2
`

type ListDocumentTypesWithDocumentCountParams struct {
	Limit  int32
	Offset int32
}

type ListDocumentTypesWithDocumentCountRow struct {
	ID            int64
	Name          string
	Description   string
	CreatedAt     sql.NullTime
	DocumentCount int64
}

func (q *Queries) ListDocumentTypesWithDocumentCount(ctx context.Context, arg ListDocumentTypesWithDocumentCountParams) ([]ListDocumentTypesWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentTypesWithDocumentCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentTypesWithDocumentCountRow
	for rows.Next() {
		var i ListDocumentTypesWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentTypeByName = `-- name: SearchDocumentTypeByName :many
SELECT id, name, description, created_at FROM document_type WHERE name LIKE $1 ORDER BY name ASC LIMIT $2
`

type SearchDocumentTypeByNameParams struct {
	Name  string
	Limit int32
}

func (q *Queries) SearchDocumentTypeByName(ctx context.Context, arg SearchDocumentTypeByNameParams) ([]DocumentType, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentTypeByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentType
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentTypeByNameWithDocumentCount = `-- name: SearchDocumentTypeByNameWithDocumentCount :many
SELECT dt.id, dt.name, dt.description, dt.created_at, COUNT(d.id) AS document_count
FROM document_type dt
LEFT JOIN document d ON dt.id = d.document_type_id
WHERE dt.name LIKE $1
GROUP BY dt.id
ORDER BY dt.name ASC LIMIT $2
`

type SearchDocumentTypeByNameWithDocumentCountParams struct {
	Name  string
	Limit int32
}

type SearchDocumentTypeByNameWithDocumentCountRow struct {
	ID            int64
	Name          string
	Description   string
	CreatedAt     sql.NullTime
	DocumentCount int64
}

func (q *Queries) SearchDocumentTypeByNameWithDocumentCount(ctx context.Context, arg SearchDocumentTypeByNameWithDocumentCountParams) ([]SearchDocumentTypeByNameWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentTypeByNameWithDocumentCount, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDocumentTypeByNameWithDocumentCountRow
	for rows.Next() {
		var i SearchDocumentTypeByNameWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentType = `-- name: UpdateDocumentType :exec
UPDATE document_type SET name = $1 WHERE id = $2
`

type UpdateDocumentTypeParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateDocumentType(ctx context.Context, arg UpdateDocumentTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentType, arg.Name, arg.ID)
	return err
}

const updateDocumentTypeFull = `-- name: UpdateDocumentTypeFull :exec
UPDATE document_type SET name = $1, description = $2 WHERE id = $3
`

type UpdateDocumentTypeFullParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateDocumentTypeFull(ctx context.Context, arg UpdateDocumentTypeFullParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentTypeFull, arg.Name, arg.Description, arg.ID)
	return err
}
