// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_type.sql

package database

import (
	"context"
	"database/sql"
)

const createDocumentType = `-- name: CreateDocumentType :execresult
INSERT INTO document_type (name) VALUES (?)
`

func (q *Queries) CreateDocumentType(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDocumentType, name)
}

const deleteDocumentType = `-- name: DeleteDocumentType :exec
DELETE FROM document_type WHERE id = ?
`

func (q *Queries) DeleteDocumentType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentType, id)
	return err
}

const getDocumentType = `-- name: GetDocumentType :one
SELECT id, name, created_at FROM document_type WHERE id = ?
`

func (q *Queries) GetDocumentType(ctx context.Context, id int64) (DocumentType, error) {
	row := q.db.QueryRowContext(ctx, getDocumentType, id)
	var i DocumentType
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAllDocumentTypes = `-- name: ListAllDocumentTypes :many
SELECT id, name, created_at FROM document_type ORDER BY created_at DESC
`

func (q *Queries) ListAllDocumentTypes(ctx context.Context) ([]DocumentType, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocumentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentType
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDocumentTypesNames = `-- name: ListAllDocumentTypesNames :many
SELECT name FROM document_type ORDER BY created_at DESC
`

func (q *Queries) ListAllDocumentTypesNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllDocumentTypesNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTypes = `-- name: ListDocumentTypes :many
SELECT id, name, created_at FROM document_type ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDocumentTypesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListDocumentTypes(ctx context.Context, arg ListDocumentTypesParams) ([]DocumentType, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentType
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentType = `-- name: UpdateDocumentType :exec
UPDATE document_type SET name = ? WHERE id = ?
`

type UpdateDocumentTypeParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateDocumentType(ctx context.Context, arg UpdateDocumentTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentType, arg.Name, arg.ID)
	return err
}
