// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_author.sql

package database

import (
	"context"
)

const addDocumentAuthor = `-- name: AddDocumentAuthor :exec
INSERT INTO document_author (document_id, author_id) VALUES (?, ?)
`

type AddDocumentAuthorParams struct {
	DocumentID int64
	AuthorID   int64
}

func (q *Queries) AddDocumentAuthor(ctx context.Context, arg AddDocumentAuthorParams) error {
	_, err := q.db.ExecContext(ctx, addDocumentAuthor, arg.DocumentID, arg.AuthorID)
	return err
}

const clearDocumentAuthors = `-- name: ClearDocumentAuthors :exec
DELETE FROM document_author WHERE document_id = ?
`

func (q *Queries) ClearDocumentAuthors(ctx context.Context, documentID int64) error {
	_, err := q.db.ExecContext(ctx, clearDocumentAuthors, documentID)
	return err
}

const getAuthorDocuments = `-- name: GetAuthorDocuments :many
SELECT d.id, d.title, d.md5_checksum, d.sha512_checksum, d.mime_type, d.file_size, d.created_at, d.modified_at, d.document_type_id, d.original_path, d.storage_path FROM document d
JOIN document_author da ON d.id = da.document_id
WHERE da.author_id = ?
`

func (q *Queries) GetAuthorDocuments(ctx context.Context, authorID int64) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorDocuments, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Md5Checksum,
			&i.Sha512Checksum,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DocumentTypeID,
			&i.OriginalPath,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentAuthors = `-- name: GetDocumentAuthors :many
SELECT a.id, a.name, a.created_at FROM author a
JOIN document_author da ON a.id = da.author_id
WHERE da.document_id = ?
`

func (q *Queries) GetDocumentAuthors(ctx context.Context, documentID int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentAuthors, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentAuthor = `-- name: RemoveDocumentAuthor :exec
DELETE FROM document_author WHERE document_id = ? AND author_id = ?
`

type RemoveDocumentAuthorParams struct {
	DocumentID int64
	AuthorID   int64
}

func (q *Queries) RemoveDocumentAuthor(ctx context.Context, arg RemoveDocumentAuthorParams) error {
	_, err := q.db.ExecContext(ctx, removeDocumentAuthor, arg.DocumentID, arg.AuthorID)
	return err
}
