// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Author struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type Document struct {
	ID             int64
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID sql.NullInt64
	OriginalPath   string
	StoragePath    string
	TextContent    sql.NullString
}

type DocumentAuthor struct {
	DocumentID int64
	AuthorID   int64
}

type DocumentFt struct {
	DocumentID string
	Title      string
	Content    string
}

type DocumentTag struct {
	DocumentID int64
	TagID      int64
}

type DocumentType struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type Task struct {
	ID          int64
	TaskID      string
	TaskName    string
	Status      string
	DocumentID  sql.NullInt64
	BatchID     sql.NullString
	FilePath    sql.NullString
	CreatedAt   sql.NullTime
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	Error       sql.NullString
}

type User struct {
	ID           int64
	Username     string
	PasswordHash sql.NullString
	ApiKey       interface{}
	CreatedAt    sql.NullTime
}
