// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
)

type Document struct {
	ID             int64
	DocumentID     string
	Title          string
	Md5Checksum    string
	Sha512Checksum string
	MimeType       string
	FileSize       int64
	PageCount      int64
	WordCount      int64
	CharCount      int64
	Language       string
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
	DocumentTypeID int64
	OriginalPath   string
	StoragePath    string
	TextContent    sql.NullString
}

type DocumentFt struct {
	DocumentID string
	Title      string
	Content    string
}

type DocumentPeople struct {
	DocumentID   int64
	PeopleID     int64
	PeopleTypeID int64
}

type DocumentTag struct {
	DocumentID int64
	TagID      int64
}

type DocumentType struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   sql.NullTime
}

type People struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type PeopleType struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   sql.NullTime
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type Task struct {
	ID          int64
	TaskID      string
	TaskType    string
	Status      string
	BatchID     sql.NullString
	Payload     json.RawMessage
	Result      *json.RawMessage
	DedupKey    sql.NullString
	CreatedAt   sql.NullTime
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	Error       sql.NullString
}

type User struct {
	ID           int64
	Username     string
	PasswordHash sql.NullString
	ApiKey       interface{}
	CreatedAt    sql.NullTime
}
