// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/wgomg/edub-kushim/internal/types"
)

type BatchSource string

const (
	BatchSourceCli             BatchSource = "cli"
	BatchSourceApi             BatchSource = "api"
	BatchSourceUpload          BatchSource = "upload"
	BatchSourcePolling         BatchSource = "polling"
	BatchSourceReenrich        BatchSource = "reenrich"
	BatchSourceOrphanedRestore BatchSource = "orphaned-restore"
	BatchSourceThumbbackfill   BatchSource = "thumbbackfill"
	BatchSourceBackup          BatchSource = "backup"
	BatchSourceMirror          BatchSource = "mirror"
	BatchSourceConfig          BatchSource = "config"
)

func (e *BatchSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchSource(s)
	case string:
		*e = BatchSource(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchSource: %T", src)
	}
	return nil
}

type NullBatchSource struct {
	BatchSource BatchSource
	Valid       bool // Valid is true if BatchSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatchSource) Scan(value interface{}) error {
	if value == nil {
		ns.BatchSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatchSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatchSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatchSource), nil
}

type BatchStatus string

const (
	BatchStatusQueued     BatchStatus = "queued"
	BatchStatusProcessing BatchStatus = "processing"
	BatchStatusCompleted  BatchStatus = "completed"
	BatchStatusFailed     BatchStatus = "failed"
	BatchStatusPaused     BatchStatus = "paused"
	BatchStatusCancelled  BatchStatus = "cancelled"
)

func (e *BatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchStatus(s)
	case string:
		*e = BatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchStatus: %T", src)
	}
	return nil
}

type NullBatchStatus struct {
	BatchStatus BatchStatus
	Valid       bool // Valid is true if BatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatchStatus), nil
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusProcessing TaskStatus = "processing"
	TaskStatusCompleted  TaskStatus = "completed"
	TaskStatusFailed     TaskStatus = "failed"
	TaskStatusCancelled  TaskStatus = "cancelled"
	TaskStatusDiscarded  TaskStatus = "discarded"
	TaskStatusWaiting    TaskStatus = "waiting"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeConsume   TaskType = "consume"
	TaskTypeEnrich    TaskType = "enrich"
	TaskTypeThumbnail TaskType = "thumbnail"
	TaskTypeBackup    TaskType = "backup"
	TaskTypeMirror    TaskType = "mirror"
	TaskTypeConfig    TaskType = "config"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType
	Valid    bool // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type BackupLock struct {
	ID        int32
	Running   bool
	StartedAt sql.NullTime
}

type Batch struct {
	ID        string
	Source    types.BatchSource
	Status    types.BatchStatus
	CreatedAt sql.NullTime
}

type BatchOwner struct {
	BatchID       string
	OwnerID       string
	Pid           int64
	AcquiredAt    time.Time
	LastHeartbeat time.Time
}

type Document struct {
	ID               int64
	DocumentID       string
	Title            string
	Md5Checksum      string
	Sha512Checksum   string
	OriginalType     string
	FileSize         int64
	PageCount        int32
	WordCount        int32
	CharCount        int32
	Language         string
	CreatedAt        sql.NullTime
	ModifiedAt       sql.NullTime
	DocumentTypeID   int64
	OriginalPath     string
	StoragePath      string
	TextContent      sql.NullString
	TextSearchVector interface{}
	DeletedAt        sql.NullTime
	HasThumbnail     bool
	ProcessedSize    int64
	TextHash         sql.NullString
}

type DocumentPeople struct {
	DocumentID   int64
	PeopleID     int64
	PeopleTypeID int64
}

type DocumentTag struct {
	DocumentID int64
	TagID      int64
}

type DocumentType struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   sql.NullTime
}

type OrphanedFile struct {
	ID              int64
	DocumentKey     string
	DocumentKeyType string
	FilePath        string
	OriginalPath    string
	SourceDir       string
	FileSize        int64
	OriginalType    string
	DetectedAt      sql.NullTime
	Status          string
	ActionAt        sql.NullTime
	ActionType      sql.NullString
}

type People struct {
	ID             int64
	Name           string
	NameNative     sql.NullString
	NormalizedName string
	CreatedAt      sql.NullTime
}

type PeopleType struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   sql.NullTime
}

type SavedSearch struct {
	ID         int64
	Name       string
	FilterJson string
	CreatedAt  time.Time
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type Task struct {
	ID          int64
	TaskID      string
	TaskType    types.TaskType
	Status      types.TaskStatus
	BatchID     sql.NullString
	Payload     *json.RawMessage
	Result      *json.RawMessage
	DedupKey    sql.NullString
	CreatedAt   sql.NullTime
	StartedAt   sql.NullTime
	CompletedAt sql.NullTime
	Error       sql.NullString
	Attempts    int32
	Progress    *json.RawMessage
}

type User struct {
	ID              int64
	Username        string
	PasswordHash    sql.NullString
	ApiKeyHash      sql.NullString
	ApiKeyPrefix    sql.NullString
	ApiKeyCreatedAt sql.NullTime
	Role            string
	CreatedAt       sql.NullTime
}
