// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orphaned.sql

package database

import (
	"context"
)

const createOrphanedFile = `-- name: CreateOrphanedFile :one
INSERT INTO orphaned_file (document_key, document_key_type, file_path, original_path, source_dir, file_size, mime_type)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type CreateOrphanedFileParams struct {
	DocumentKey     string
	DocumentKeyType string
	FilePath        string
	OriginalPath    string
	SourceDir       string
	FileSize        int64
	MimeType        string
}

func (q *Queries) CreateOrphanedFile(ctx context.Context, arg CreateOrphanedFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrphanedFile,
		arg.DocumentKey,
		arg.DocumentKeyType,
		arg.FilePath,
		arg.OriginalPath,
		arg.SourceDir,
		arg.FileSize,
		arg.MimeType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrphanedFile = `-- name: GetOrphanedFile :one
SELECT id, document_key, document_key_type, file_path, original_path, source_dir, file_size, mime_type, detected_at, status, action_at, action_type FROM orphaned_file WHERE id = $1
`

func (q *Queries) GetOrphanedFile(ctx context.Context, id int64) (OrphanedFile, error) {
	row := q.db.QueryRowContext(ctx, getOrphanedFile, id)
	var i OrphanedFile
	err := row.Scan(
		&i.ID,
		&i.DocumentKey,
		&i.DocumentKeyType,
		&i.FilePath,
		&i.OriginalPath,
		&i.SourceDir,
		&i.FileSize,
		&i.MimeType,
		&i.DetectedAt,
		&i.Status,
		&i.ActionAt,
		&i.ActionType,
	)
	return i, err
}

const listOrphanedFiles = `-- name: ListOrphanedFiles :many
SELECT id, document_key, document_key_type, file_path, original_path, source_dir, file_size, mime_type, detected_at, status, action_at, action_type FROM orphaned_file WHERE status = 'pending' ORDER BY detected_at DESC
`

func (q *Queries) ListOrphanedFiles(ctx context.Context) ([]OrphanedFile, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphanedFile
	for rows.Next() {
		var i OrphanedFile
		if err := rows.Scan(
			&i.ID,
			&i.DocumentKey,
			&i.DocumentKeyType,
			&i.FilePath,
			&i.OriginalPath,
			&i.SourceDir,
			&i.FileSize,
			&i.MimeType,
			&i.DetectedAt,
			&i.Status,
			&i.ActionAt,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllOrphanedFilesDeleted = `-- name: MarkAllOrphanedFilesDeleted :exec
UPDATE orphaned_file SET status = 'deleted', action_at = CURRENT_TIMESTAMP, action_type = 'delete' WHERE status = 'pending'
`

func (q *Queries) MarkAllOrphanedFilesDeleted(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllOrphanedFilesDeleted)
	return err
}

const markOrphanedFileDeleted = `-- name: MarkOrphanedFileDeleted :exec
UPDATE orphaned_file SET status = 'deleted', action_at = CURRENT_TIMESTAMP, action_type = 'delete' WHERE id = $1
`

func (q *Queries) MarkOrphanedFileDeleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOrphanedFileDeleted, id)
	return err
}

const markOrphanedFileReingested = `-- name: MarkOrphanedFileReingested :exec
UPDATE orphaned_file SET status = 'reingested', action_at = CURRENT_TIMESTAMP, action_type = 'move_to_inbox' WHERE id = $1
`

func (q *Queries) MarkOrphanedFileReingested(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOrphanedFileReingested, id)
	return err
}

const markOrphanedFileRestored = `-- name: MarkOrphanedFileRestored :exec
UPDATE orphaned_file SET status = 'restored', action_at = CURRENT_TIMESTAMP, action_type = 'restore' WHERE id = $1
`

func (q *Queries) MarkOrphanedFileRestored(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOrphanedFileRestored, id)
	return err
}
