// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people_type.sql

package database

import (
	"context"
)

const createPeopleType = `-- name: CreatePeopleType :one
INSERT INTO people_type (name, description) VALUES ($1, $2) RETURNING id
`

type CreatePeopleTypeParams struct {
	Name        string
	Description string
}

func (q *Queries) CreatePeopleType(ctx context.Context, arg CreatePeopleTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPeopleType, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePeopleType = `-- name: DeletePeopleType :exec
DELETE FROM people_type WHERE id = $1
`

func (q *Queries) DeletePeopleType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePeopleType, id)
	return err
}

const getPeopleType = `-- name: GetPeopleType :one
SELECT id, name, description, created_at FROM people_type WHERE id = $1
`

func (q *Queries) GetPeopleType(ctx context.Context, id int64) (PeopleType, error) {
	row := q.db.QueryRowContext(ctx, getPeopleType, id)
	var i PeopleType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPeopleTypeByName = `-- name: GetPeopleTypeByName :one
SELECT id, name, description, created_at FROM people_type WHERE name = $1
`

func (q *Queries) GetPeopleTypeByName(ctx context.Context, name string) (PeopleType, error) {
	row := q.db.QueryRowContext(ctx, getPeopleTypeByName, name)
	var i PeopleType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPeopleTypes = `-- name: ListAllPeopleTypes :many
SELECT id, name, description, created_at FROM people_type ORDER BY created_at DESC
`

func (q *Queries) ListAllPeopleTypes(ctx context.Context) ([]PeopleType, error) {
	rows, err := q.db.QueryContext(ctx, listAllPeopleTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeopleType
	for rows.Next() {
		var i PeopleType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPeopleTypesNames = `-- name: ListAllPeopleTypesNames :many
SELECT name FROM people_type ORDER BY created_at DESC
`

func (q *Queries) ListAllPeopleTypesNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllPeopleTypesNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleTypes = `-- name: ListPeopleTypes :many
SELECT id, name, description, created_at FROM people_type ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPeopleTypesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPeopleTypes(ctx context.Context, arg ListPeopleTypesParams) ([]PeopleType, error) {
	rows, err := q.db.QueryContext(ctx, listPeopleTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeopleType
	for rows.Next() {
		var i PeopleType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeopleTypeByName = `-- name: SearchPeopleTypeByName :many
SELECT id, name, description, created_at FROM people_type WHERE name LIKE $1 ORDER BY name ASC LIMIT $2
`

type SearchPeopleTypeByNameParams struct {
	Name  string
	Limit int32
}

func (q *Queries) SearchPeopleTypeByName(ctx context.Context, arg SearchPeopleTypeByNameParams) ([]PeopleType, error) {
	rows, err := q.db.QueryContext(ctx, searchPeopleTypeByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeopleType
	for rows.Next() {
		var i PeopleType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeopleType = `-- name: UpdatePeopleType :exec
UPDATE people_type SET name = $1, description = $2 WHERE id = $3
`

type UpdatePeopleTypeParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdatePeopleType(ctx context.Context, arg UpdatePeopleTypeParams) error {
	_, err := q.db.ExecContext(ctx, updatePeopleType, arg.Name, arg.Description, arg.ID)
	return err
}
