// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people.sql

package database

import (
	"context"
	"database/sql"
)

const countPeople = `-- name: CountPeople :one
SELECT COUNT(*) FROM people
`

func (q *Queries) CountPeople(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPeople)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPeopleByName = `-- name: CountPeopleByName :one
SELECT COUNT(*) FROM people WHERE name LIKE $1
`

func (q *Queries) CountPeopleByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPeopleByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPeople = `-- name: CreatePeople :one
INSERT INTO people (name, name_native, normalized_name)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO NOTHING
RETURNING id
`

type CreatePeopleParams struct {
	Name           string
	NameNative     sql.NullString
	NormalizedName string
}

func (q *Queries) CreatePeople(ctx context.Context, arg CreatePeopleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPeople, arg.Name, arg.NameNative, arg.NormalizedName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePeople = `-- name: DeletePeople :exec
DELETE FROM people WHERE id = $1
`

func (q *Queries) DeletePeople(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePeople, id)
	return err
}

const getPeople = `-- name: GetPeople :one
SELECT id, name, name_native, normalized_name, created_at FROM people WHERE id = $1
`

func (q *Queries) GetPeople(ctx context.Context, id int64) (People, error) {
	row := q.db.QueryRowContext(ctx, getPeople, id)
	var i People
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNative,
		&i.NormalizedName,
		&i.CreatedAt,
	)
	return i, err
}

const getPeopleByName = `-- name: GetPeopleByName :one
SELECT id, name, name_native, normalized_name, created_at FROM people WHERE name = $1
`

func (q *Queries) GetPeopleByName(ctx context.Context, name string) (People, error) {
	row := q.db.QueryRowContext(ctx, getPeopleByName, name)
	var i People
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNative,
		&i.NormalizedName,
		&i.CreatedAt,
	)
	return i, err
}

const getPeopleByNormalizedName = `-- name: GetPeopleByNormalizedName :one
SELECT id, name, name_native, normalized_name, created_at FROM people WHERE normalized_name = $1
`

func (q *Queries) GetPeopleByNormalizedName(ctx context.Context, normalizedName string) (People, error) {
	row := q.db.QueryRowContext(ctx, getPeopleByNormalizedName, normalizedName)
	var i People
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNative,
		&i.NormalizedName,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPeople = `-- name: ListAllPeople :many
SELECT id, name, name_native, normalized_name, created_at FROM people ORDER BY created_at DESC
`

func (q *Queries) ListAllPeople(ctx context.Context) ([]People, error) {
	rows, err := q.db.QueryContext(ctx, listAllPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []People
	for rows.Next() {
		var i People
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.NormalizedName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeople = `-- name: ListPeople :many
SELECT id, name, name_native, normalized_name, created_at FROM people ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPeopleParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPeople(ctx context.Context, arg ListPeopleParams) ([]People, error) {
	rows, err := q.db.QueryContext(ctx, listPeople, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []People
	for rows.Next() {
		var i People
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.NormalizedName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleWithDocumentCount = `-- name: ListPeopleWithDocumentCount :many
SELECT p.id, p.name, p.name_native, p.normalized_name, p.created_at, COUNT(dp.document_id) AS document_count
FROM people p
LEFT JOIN document_people dp ON p.id = dp.people_id
LEFT JOIN document d ON dp.document_id = d.id AND d.deleted_at IS NULL
GROUP BY p.id
ORDER BY p.created_at DESC LIMIT $1 OFFSET $2
`

type ListPeopleWithDocumentCountParams struct {
	Limit  int32
	Offset int32
}

type ListPeopleWithDocumentCountRow struct {
	ID             int64
	Name           string
	NameNative     sql.NullString
	NormalizedName string
	CreatedAt      sql.NullTime
	DocumentCount  int64
}

func (q *Queries) ListPeopleWithDocumentCount(ctx context.Context, arg ListPeopleWithDocumentCountParams) ([]ListPeopleWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listPeopleWithDocumentCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeopleWithDocumentCountRow
	for rows.Next() {
		var i ListPeopleWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.NormalizedName,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeopleByName = `-- name: SearchPeopleByName :many
SELECT id, name, name_native, normalized_name, created_at FROM people WHERE name LIKE $1 ORDER BY name ASC LIMIT $2
`

type SearchPeopleByNameParams struct {
	Name  string
	Limit int32
}

func (q *Queries) SearchPeopleByName(ctx context.Context, arg SearchPeopleByNameParams) ([]People, error) {
	rows, err := q.db.QueryContext(ctx, searchPeopleByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []People
	for rows.Next() {
		var i People
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.NormalizedName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeopleByNameWithDocumentCount = `-- name: SearchPeopleByNameWithDocumentCount :many
SELECT p.id, p.name, p.name_native, p.normalized_name, p.created_at, COUNT(dp.document_id) AS document_count
FROM people p
LEFT JOIN document_people dp ON p.id = dp.people_id
LEFT JOIN document d ON dp.document_id = d.id AND d.deleted_at IS NULL
WHERE p.name LIKE $1
GROUP BY p.id
ORDER BY p.name ASC LIMIT $2 OFFSET $3
`

type SearchPeopleByNameWithDocumentCountParams struct {
	Name   string
	Limit  int32
	Offset int32
}

type SearchPeopleByNameWithDocumentCountRow struct {
	ID             int64
	Name           string
	NameNative     sql.NullString
	NormalizedName string
	CreatedAt      sql.NullTime
	DocumentCount  int64
}

func (q *Queries) SearchPeopleByNameWithDocumentCount(ctx context.Context, arg SearchPeopleByNameWithDocumentCountParams) ([]SearchPeopleByNameWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPeopleByNameWithDocumentCount, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPeopleByNameWithDocumentCountRow
	for rows.Next() {
		var i SearchPeopleByNameWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.NormalizedName,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeople = `-- name: UpdatePeople :exec
UPDATE people SET
    name = $1, normalized_name = $2
WHERE id = $3
`

type UpdatePeopleParams struct {
	Name           string
	NormalizedName string
	ID             int64
}

func (q *Queries) UpdatePeople(ctx context.Context, arg UpdatePeopleParams) error {
	_, err := q.db.ExecContext(ctx, updatePeople, arg.Name, arg.NormalizedName, arg.ID)
	return err
}

const updatePeopleFull = `-- name: UpdatePeopleFull :exec
UPDATE people SET name = $1, name_native = $2, normalized_name = $3 WHERE id = $4
`

type UpdatePeopleFullParams struct {
	Name           string
	NameNative     sql.NullString
	NormalizedName string
	ID             int64
}

func (q *Queries) UpdatePeopleFull(ctx context.Context, arg UpdatePeopleFullParams) error {
	_, err := q.db.ExecContext(ctx, updatePeopleFull,
		arg.Name,
		arg.NameNative,
		arg.NormalizedName,
		arg.ID,
	)
	return err
}

const updatePeopleNative = `-- name: UpdatePeopleNative :exec
UPDATE people SET
    name_native = $1
WHERE id = $2 AND name_native IS NULL
`

type UpdatePeopleNativeParams struct {
	NameNative sql.NullString
	ID         int64
}

func (q *Queries) UpdatePeopleNative(ctx context.Context, arg UpdatePeopleNativeParams) error {
	_, err := q.db.ExecContext(ctx, updatePeopleNative, arg.NameNative, arg.ID)
	return err
}
