// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people.sql

package database

import (
	"context"
	"database/sql"
)

const createPeople = `-- name: CreatePeople :execresult
INSERT OR IGNORE INTO people (
    name, name_native
) VALUES (?, ?)
`

type CreatePeopleParams struct {
	Name       string
	NameNative sql.NullString
}

func (q *Queries) CreatePeople(ctx context.Context, arg CreatePeopleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPeople, arg.Name, arg.NameNative)
}

const deletePeople = `-- name: DeletePeople :exec
DELETE FROM people WHERE id = ?
`

func (q *Queries) DeletePeople(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePeople, id)
	return err
}

const getPeople = `-- name: GetPeople :one
SELECT id, name, name_native, created_at FROM people WHERE id = ?
`

func (q *Queries) GetPeople(ctx context.Context, id int64) (People, error) {
	row := q.db.QueryRowContext(ctx, getPeople, id)
	var i People
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNative,
		&i.CreatedAt,
	)
	return i, err
}

const getPeopleByName = `-- name: GetPeopleByName :one
SELECT id, name, name_native, created_at FROM people WHERE name = ?
`

func (q *Queries) GetPeopleByName(ctx context.Context, name string) (People, error) {
	row := q.db.QueryRowContext(ctx, getPeopleByName, name)
	var i People
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNative,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPeople = `-- name: ListAllPeople :many
SELECT id, name, name_native, created_at FROM people ORDER BY created_at DESC
`

func (q *Queries) ListAllPeople(ctx context.Context) ([]People, error) {
	rows, err := q.db.QueryContext(ctx, listAllPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []People
	for rows.Next() {
		var i People
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeople = `-- name: ListPeople :many
SELECT id, name, name_native, created_at FROM people ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListPeopleParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPeople(ctx context.Context, arg ListPeopleParams) ([]People, error) {
	rows, err := q.db.QueryContext(ctx, listPeople, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []People
	for rows.Next() {
		var i People
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeopleByName = `-- name: SearchPeopleByName :many
SELECT id, name, name_native, created_at FROM people WHERE name LIKE ? ORDER BY name ASC LIMIT ?
`

type SearchPeopleByNameParams struct {
	Name  string
	Limit int64
}

func (q *Queries) SearchPeopleByName(ctx context.Context, arg SearchPeopleByNameParams) ([]People, error) {
	rows, err := q.db.QueryContext(ctx, searchPeopleByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []People
	for rows.Next() {
		var i People
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNative,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeople = `-- name: UpdatePeople :exec
UPDATE people SET
    name = ?
WHERE id = ?
`

type UpdatePeopleParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdatePeople(ctx context.Context, arg UpdatePeopleParams) error {
	_, err := q.db.ExecContext(ctx, updatePeople, arg.Name, arg.ID)
	return err
}

const updatePeopleFull = `-- name: UpdatePeopleFull :exec
UPDATE people SET name = ?, name_native = ? WHERE id = ?
`

type UpdatePeopleFullParams struct {
	Name       string
	NameNative sql.NullString
	ID         int64
}

func (q *Queries) UpdatePeopleFull(ctx context.Context, arg UpdatePeopleFullParams) error {
	_, err := q.db.ExecContext(ctx, updatePeopleFull, arg.Name, arg.NameNative, arg.ID)
	return err
}

const updatePeopleNative = `-- name: UpdatePeopleNative :exec
UPDATE people SET
    name_native = ?
WHERE id = ? AND name_native IS NULL
`

type UpdatePeopleNativeParams struct {
	NameNative sql.NullString
	ID         int64
}

func (q *Queries) UpdatePeopleNative(ctx context.Context, arg UpdatePeopleNativeParams) error {
	_, err := q.db.ExecContext(ctx, updatePeopleNative, arg.NameNative, arg.ID)
	return err
}
