// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_search.sql

package database

import (
	"context"
)

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO saved_search (name, filter_json) VALUES ($1, $2) RETURNING id
`

type CreateSavedSearchParams struct {
	Name       string
	FilterJson string
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSavedSearch, arg.Name, arg.FilterJson)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :exec
DELETE FROM saved_search WHERE id = $1
`

func (q *Queries) DeleteSavedSearch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSavedSearch, id)
	return err
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, name, filter_json, created_at FROM saved_search ORDER BY created_at DESC
`

func (q *Queries) ListSavedSearches(ctx context.Context) ([]SavedSearch, error) {
	rows, err := q.db.QueryContext(ctx, listSavedSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FilterJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
