// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package database

import (
	"context"
	"database/sql"
)

const createTag = `-- name: CreateTag :execresult
INSERT INTO tag (
    name
) VALUES (?)
`

func (q *Queries) CreateTag(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTag, name)
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tag WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at FROM tag WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tag ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListTagsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tag SET
    name = ?
WHERE id = ?
`

type UpdateTagParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag, arg.Name, arg.ID)
	return err
}
