// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package database

import (
	"context"
	"database/sql"
)

const countTags = `-- name: CountTags :one
SELECT COUNT(*) FROM tag
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagsByName = `-- name: CountTagsByName :one
SELECT COUNT(*) FROM tag WHERE name LIKE $1
`

func (q *Queries) CountTagsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :execresult
INSERT INTO tag (name)
VALUES ($1)
ON CONFLICT (name) DO NOTHING
`

func (q *Queries) CreateTag(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTag, name)
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tag WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at FROM tag WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tag WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, created_at FROM tag ORDER BY created_at DESC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTagsNames = `-- name: ListAllTagsNames :many
SELECT name FROM tag ORDER BY created_at DESC
`

func (q *Queries) ListAllTagsNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllTagsNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tag ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithDocumentCount = `-- name: ListTagsWithDocumentCount :many
SELECT t.id, t.name, t.created_at, COUNT(dt.document_id) AS document_count
FROM tag t
LEFT JOIN document_tag dt ON t.id = dt.tag_id
GROUP BY t.id
ORDER BY t.created_at DESC LIMIT $1 OFFSET $2
`

type ListTagsWithDocumentCountParams struct {
	Limit  int32
	Offset int32
}

type ListTagsWithDocumentCountRow struct {
	ID            int64
	Name          string
	CreatedAt     sql.NullTime
	DocumentCount int64
}

func (q *Queries) ListTagsWithDocumentCount(ctx context.Context, arg ListTagsWithDocumentCountParams) ([]ListTagsWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithDocumentCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsWithDocumentCountRow
	for rows.Next() {
		var i ListTagsWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTagsByName = `-- name: SearchTagsByName :many
SELECT id, name, created_at FROM tag WHERE name LIKE $1 ORDER BY name ASC LIMIT $2 OFFSET $3
`

type SearchTagsByNameParams struct {
	Name   string
	Limit  int32
	Offset int32
}

func (q *Queries) SearchTagsByName(ctx context.Context, arg SearchTagsByNameParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, searchTagsByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTagsByNameWithDocumentCount = `-- name: SearchTagsByNameWithDocumentCount :many
SELECT t.id, t.name, t.created_at, COUNT(dt.document_id) AS document_count
FROM tag t
LEFT JOIN document_tag dt ON t.id = dt.tag_id
WHERE t.name LIKE $1
GROUP BY t.id
ORDER BY t.name ASC LIMIT $2 OFFSET $3
`

type SearchTagsByNameWithDocumentCountParams struct {
	Name   string
	Limit  int32
	Offset int32
}

type SearchTagsByNameWithDocumentCountRow struct {
	ID            int64
	Name          string
	CreatedAt     sql.NullTime
	DocumentCount int64
}

func (q *Queries) SearchTagsByNameWithDocumentCount(ctx context.Context, arg SearchTagsByNameWithDocumentCountParams) ([]SearchTagsByNameWithDocumentCountRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTagsByNameWithDocumentCount, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagsByNameWithDocumentCountRow
	for rows.Next() {
		var i SearchTagsByNameWithDocumentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tag SET
    name = $1
WHERE id = $2
`

type UpdateTagParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag, arg.Name, arg.ID)
	return err
}
