// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag_verdict_event.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
	"github.com/wgomg/edub-kushim/internal/types"
)

const insertTagVerdictEvent = `-- name: InsertTagVerdictEvent :execrows
INSERT INTO tag_verdict_event
    (document_id, query, target, sim, verdict, verdict_model, policy_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (query, target, policy_version) WHERE verdict_model IS NOT NULL DO NOTHING
`

type InsertTagVerdictEventParams struct {
	DocumentID    int64
	Query         string
	Target        string
	Sim           float64
	Verdict       types.TagVerdict
	VerdictModel  sql.NullString
	PolicyVersion string
}

func (q *Queries) InsertTagVerdictEvent(ctx context.Context, arg InsertTagVerdictEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTagVerdictEvent,
		arg.DocumentID,
		arg.Query,
		arg.Target,
		arg.Sim,
		arg.Verdict,
		arg.VerdictModel,
		arg.PolicyVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const latestTagVerdictsForPairs = `-- name: LatestTagVerdictsForPairs :many
SELECT DISTINCT ON (query, target)
       query, target, verdict, verdict_model, policy_version, verdict_at
FROM tag_verdict_event
WHERE policy_version = $1
  AND (query, target) IN (SELECT unnest($2::text[]), unnest($3::text[]))
ORDER BY query, target, verdict_at DESC
`

type LatestTagVerdictsForPairsParams struct {
	PolicyVersion string
	Queries       []string
	Targets       []string
}

type LatestTagVerdictsForPairsRow struct {
	Query         string
	Target        string
	Verdict       types.TagVerdict
	VerdictModel  sql.NullString
	PolicyVersion string
	VerdictAt     time.Time
}

func (q *Queries) LatestTagVerdictsForPairs(ctx context.Context, arg LatestTagVerdictsForPairsParams) ([]LatestTagVerdictsForPairsRow, error) {
	rows, err := q.db.QueryContext(ctx, latestTagVerdictsForPairs, arg.PolicyVersion, pq.Array(arg.Queries), pq.Array(arg.Targets))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestTagVerdictsForPairsRow
	for rows.Next() {
		var i LatestTagVerdictsForPairsRow
		if err := rows.Scan(
			&i.Query,
			&i.Target,
			&i.Verdict,
			&i.VerdictModel,
			&i.PolicyVersion,
			&i.VerdictAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
