// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package database

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE task SET
    status = 'completed',
    completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :execresult
INSERT INTO task (
    task_id, task_name, status, document_id
) VALUES (?, ?, ?, ?)
`

type CreateTaskParams struct {
	TaskID     string
	TaskName   string
	Status     string
	DocumentID sql.NullInt64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.TaskID,
		arg.TaskName,
		arg.Status,
		arg.DocumentID,
	)
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const failTask = `-- name: FailTask :exec
UPDATE task SET
    status = 'failed',
    completed_at = CURRENT_TIMESTAMP,
    error = ?
WHERE id = ?
`

type FailTaskParams struct {
	Error sql.NullString
	ID    int64
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.ExecContext(ctx, failTask, arg.Error, arg.ID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, task_id, task_name, status, document_id, created_at, started_at, completed_at, error FROM task WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskName,
		&i.Status,
		&i.DocumentID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const getTaskByTaskID = `-- name: GetTaskByTaskID :one
SELECT id, task_id, task_name, status, document_id, created_at, started_at, completed_at, error FROM task WHERE task_id = ?
`

func (q *Queries) GetTaskByTaskID(ctx context.Context, taskID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByTaskID, taskID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskName,
		&i.Status,
		&i.DocumentID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, task_id, task_name, status, document_id, created_at, started_at, completed_at, error
FROM task ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListTasksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskName,
			&i.Status,
			&i.DocumentID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByDocument = `-- name: ListTasksByDocument :many
SELECT id, task_id, task_name, status, document_id, created_at, started_at, completed_at, error
FROM task WHERE document_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTasksByDocument(ctx context.Context, documentID sql.NullInt64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskName,
			&i.Status,
			&i.DocumentID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, task_id, task_name, status, document_id, created_at, started_at, completed_at, error
FROM task WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListTasksByStatusParams struct {
	Status string
	Limit  int64
	Offset int64
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskName,
			&i.Status,
			&i.DocumentID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTask = `-- name: StartTask :exec
UPDATE task SET
    status = 'processing',
    started_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) StartTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startTask, id)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task SET status = ?, error = ? WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string
	Error  sql.NullString
	ID     int64
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.Error, arg.ID)
	return err
}
