// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const claimTask = `-- name: ClaimTask :execrows
UPDATE task SET
    status = 'processing',
    started_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 'pending'
`

func (q *Queries) ClaimTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeTask = `-- name: CompleteTask :exec
UPDATE task SET
    status = 'completed',
    result = ?,
    completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type CompleteTaskParams struct {
	Result *json.RawMessage
	ID     int64
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, completeTask, arg.Result, arg.ID)
	return err
}

const countTasksByBatchAndStatus = `-- name: CountTasksByBatchAndStatus :one
SELECT COUNT(*) FROM task WHERE batch_id = ? AND status = ?
`

type CountTasksByBatchAndStatusParams struct {
	BatchID sql.NullString
	Status  string
}

func (q *Queries) CountTasksByBatchAndStatus(ctx context.Context, arg CountTasksByBatchAndStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByBatchAndStatus, arg.BatchID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :execresult
INSERT INTO task (
    task_id, task_type, status, batch_id, payload, dedup_key
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	TaskID   string
	TaskType string
	Status   string
	BatchID  sql.NullString
	Payload  json.RawMessage
	DedupKey sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.TaskID,
		arg.TaskType,
		arg.Status,
		arg.BatchID,
		arg.Payload,
		arg.DedupKey,
	)
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const failTask = `-- name: FailTask :exec
UPDATE task SET
    status = 'failed',
    completed_at = CURRENT_TIMESTAMP,
    error = ?
WHERE id = ?
`

type FailTaskParams struct {
	Error sql.NullString
	ID    int64
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.ExecContext(ctx, failTask, arg.Error, arg.ID)
	return err
}

const getNextPendingTask = `-- name: GetNextPendingTask :one
SELECT id FROM task WHERE status = 'pending' ORDER BY created_at LIMIT 1
`

func (q *Queries) GetNextPendingTask(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingTask)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getNextPendingTaskOfType = `-- name: GetNextPendingTaskOfType :one
SELECT id FROM task
WHERE status = 'pending' AND task_type = ?
ORDER BY created_at LIMIT 1
`

func (q *Queries) GetNextPendingTaskOfType(ctx context.Context, taskType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingTaskOfType, taskType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTask = `-- name: GetTask :one
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key, created_at, started_at, completed_at, error FROM task WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskType,
		&i.Status,
		&i.BatchID,
		&i.Payload,
		&i.Result,
		&i.DedupKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const getTaskByBatchID = `-- name: GetTaskByBatchID :many
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key, created_at, started_at, completed_at, error FROM task WHERE batch_id = ? ORDER BY created_at
`

func (q *Queries) GetTaskByBatchID(ctx context.Context, batchID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTaskByBatchID, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskType,
			&i.Status,
			&i.BatchID,
			&i.Payload,
			&i.Result,
			&i.DedupKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByTaskID = `-- name: GetTaskByTaskID :one
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key, created_at, started_at, completed_at, error FROM task WHERE task_id = ?
`

func (q *Queries) GetTaskByTaskID(ctx context.Context, taskID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByTaskID, taskID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskType,
		&i.Status,
		&i.BatchID,
		&i.Payload,
		&i.Result,
		&i.DedupKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key,
       created_at, started_at, completed_at, error
FROM task ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListTasksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskType,
			&i.Status,
			&i.BatchID,
			&i.Payload,
			&i.Result,
			&i.DedupKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByBatch = `-- name: ListTasksByBatch :many
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key,
       created_at, started_at, completed_at, error
FROM task WHERE batch_id = ? ORDER BY created_at
`

func (q *Queries) ListTasksByBatch(ctx context.Context, batchID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskType,
			&i.Status,
			&i.BatchID,
			&i.Payload,
			&i.Result,
			&i.DedupKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByBatchAndStatus = `-- name: ListTasksByBatchAndStatus :many
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key,
       created_at, started_at, completed_at, error
FROM task WHERE batch_id = ? AND status = ? ORDER BY created_at
`

type ListTasksByBatchAndStatusParams struct {
	BatchID sql.NullString
	Status  string
}

func (q *Queries) ListTasksByBatchAndStatus(ctx context.Context, arg ListTasksByBatchAndStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByBatchAndStatus, arg.BatchID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskType,
			&i.Status,
			&i.BatchID,
			&i.Payload,
			&i.Result,
			&i.DedupKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, task_id, task_type, status, batch_id, payload, result, dedup_key,
       created_at, started_at, completed_at, error
FROM task WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListTasksByStatusParams struct {
	Status string
	Limit  int64
	Offset int64
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskType,
			&i.Status,
			&i.BatchID,
			&i.Payload,
			&i.Result,
			&i.DedupKey,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryTask = `-- name: RetryTask :exec
UPDATE task SET
    status = 'pending',
    result = NULL,
    error = NULL,
    started_at = NULL,
    completed_at = NULL
WHERE id = ?
`

func (q *Queries) RetryTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, retryTask, id)
	return err
}
