// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM user
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO user (
    username,
    password_hash,
    role,
    api_key_hash,
    api_key_prefix,
    api_key_created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username        string
	PasswordHash    sql.NullString
	Role            string
	ApiKeyHash      sql.NullString
	ApiKeyPrefix    sql.NullString
	ApiKeyCreatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.ApiKeyHash,
		arg.ApiKeyPrefix,
		arg.ApiKeyCreatedAt,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, api_key_hash, created_at, api_key_prefix, api_key_created_at, role FROM user WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.ApiKeyPrefix,
		&i.ApiKeyCreatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByAPIKeyHash = `-- name: GetUserByAPIKeyHash :one
SELECT id, username, password_hash, api_key_hash, created_at, api_key_prefix, api_key_created_at, role FROM user WHERE api_key_hash = ?
`

func (q *Queries) GetUserByAPIKeyHash(ctx context.Context, apiKeyHash sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKeyHash, apiKeyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.ApiKeyPrefix,
		&i.ApiKeyCreatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, api_key_hash, created_at, api_key_prefix, api_key_created_at, role FROM user WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.ApiKeyPrefix,
		&i.ApiKeyCreatedAt,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, api_key_prefix, api_key_created_at, created_at
FROM user ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64
	Offset int64
}

type ListUsersRow struct {
	ID              int64
	Username        string
	Role            string
	ApiKeyPrefix    sql.NullString
	ApiKeyCreatedAt sql.NullTime
	CreatedAt       sql.NullTime
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.ApiKeyPrefix,
			&i.ApiKeyCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserAPIKey = `-- name: RevokeUserAPIKey :execresult
UPDATE user SET
    api_key_hash = NULL,
    api_key_prefix = NULL,
    api_key_created_at = NULL
WHERE id = ?
`

func (q *Queries) RevokeUserAPIKey(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeUserAPIKey, id)
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user SET
    username = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username string
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Username, arg.ID)
	return err
}

const updateUserAPIKey = `-- name: UpdateUserAPIKey :execresult
UPDATE user SET
    api_key_hash = ?,
    api_key_prefix = ?,
    api_key_created_at = ?
WHERE id = ?
`

type UpdateUserAPIKeyParams struct {
	ApiKeyHash      sql.NullString
	ApiKeyPrefix    sql.NullString
	ApiKeyCreatedAt sql.NullTime
	ID              int64
}

func (q *Queries) UpdateUserAPIKey(ctx context.Context, arg UpdateUserAPIKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserAPIKey,
		arg.ApiKeyHash,
		arg.ApiKeyPrefix,
		arg.ApiKeyCreatedAt,
		arg.ID,
	)
}

const updateUserCredentials = `-- name: UpdateUserCredentials :exec
UPDATE user SET username = ?, password_hash = ? WHERE id = ?
`

type UpdateUserCredentialsParams struct {
	Username     string
	PasswordHash sql.NullString
	ID           int64
}

func (q *Queries) UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCredentials, arg.Username, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user SET
    password_hash = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash sql.NullString
	ID           int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE user SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role string
	ID   int64
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
