FROM alpine:3.21

RUN apk add --no-cache \
    gcc musl-dev g++ make autoconf automake libtool pkgconfig linux-headers git curl \
    rust cargo \
    libstdc++-dev \
    zlib-dev zlib-static \
    freetype-dev harfbuzz-dev jpeg-dev openjpeg-dev \
    oniguruma-dev

RUN curl -fsSL https://go.dev/dl/go1.26.4.linux-amd64.tar.gz | \
    tar -C /usr/local -xz && \
    rm -f go1.26.4.linux-amd64.tar.gz

ENV PATH=/usr/local/go/bin:$PATH
ENV GOMODCACHE=/go/pkg/mod

RUN apk add --no-cache ca-certificates && update-ca-certificates

WORKDIR /workspace
