INSERT OR IGNORE INTO tag (name) VALUES
-- 000: Computer science, information & general works
('computer science'),
('information science'),
('journalism'),
('python'),
('javascript'),
('java'),
('c++'),
('rust'),
('go'),
('museology'),

-- 100: Philosophy & psychology
('metaphysics'),
('epistemology'),
('logic'),
('ethics'),
('psychology'),

-- 200: Religion
('religion'),
('theology'),
('comparative religion'),
('christianism'),
('islam'),
('hinduism'),
('buddhism'),
('judaism'),

-- 300: Social sciences
('economics'),
('marxism'),
('liberalism'),
('anarchism'),
('conservatism'),
('socialism'),
('fascism'),
('law'),
('military science'),
('education'),
('folklore'),
('criminology'),
('finance'),
('international relations'),
('human rights'),
('demography'),
('migration'),
('urban planning'),
('sociology'),
('statistics'),
('anthropology'),

-- 400: Language
('language'),
('linguistics'),

-- 500: Science
('mathematics'),
('astronomy'),
('physics'),
('chemistry'),
('geology'),
('paleontology'),
('botany'),
('zoology'),
('ecology'),
('climatology'),
('genetics'),
('marine biology'),
('microbiology'),
('neuroscience'),

-- 600: Technology
('agriculture'),
('management'),
('chemical engineering'),
('manufacturing'),
('construction'),
('aerospace'),
('robotics'),
('artificial intelligence'),
('nanotechnology'),
('telecommunications'),
('energy'),
('cybersecurity'),
('mechanical engineering'),
('electrical engineering'),
('public health'),
('epidemiology'),
('nutrition'),

-- 700: Arts & recreation
('architecture'),
('sculpture'),
('drawing'),
('painting'),
('printmaking'),
('photography'),
('music'),
('sports'),
('theater'),
('dance'),
('film'),
('fashion'),

-- 800: Literature
('literature'),
('poetry'),
('drama'),
('science fiction'),
('fantasy'),
('horror'),
('mystery'),

-- 900: History & geography
('geography'),
('biography'),
('genealogy'),
('archaeology'),
('colonialism'),
('ancient history'),
('medieval history'),
('modern history'),
('historiography');
