INSERT INTO tag (name)
VALUES
    ('computer science'),
    ('information science'),
    ('journalism'),
    ('python'),
    ('javascript'),
    ('java'),
    ('c++'),
    ('rust'),
    ('go'),
    ('museology'),
    ('metaphysics'),
    ('epistemology'),
    ('logic'),
    ('ethics'),
    ('psychology'),
    ('religion'),
    ('theology'),
    ('comparative religion'),
    ('christianism'),
    ('islam'),
    ('hinduism'),
    ('buddhism'),
    ('judaism'),
    ('economics'),
    ('marxism'),
    ('liberalism'),
    ('anarchism'),
    ('conservatism'),
    ('socialism'),
    ('fascism'),
    ('law'),
    ('military science'),
    ('education'),
    ('folklore'),
    ('criminology'),
    ('finance'),
    ('international relations'),
    ('human rights'),
    ('demography'),
    ('migration'),
    ('urban planning'),
    ('sociology'),
    ('statistics'),
    ('anthropology'),
    ('language'),
    ('linguistics'),
    ('mathematics'),
    ('astronomy'),
    ('physics'),
    ('chemistry'),
    ('geology'),
    ('paleontology'),
    ('botany'),
    ('zoology'),
    ('ecology'),
    ('climatology'),
    ('genetics'),
    ('marine biology'),
    ('microbiology'),
    ('neuroscience'),
    ('agriculture'),
    ('management'),
    ('chemical engineering'),
    ('manufacturing'),
    ('construction'),
    ('aerospace'),
    ('robotics'),
    ('artificial intelligence'),
    ('nanotechnology'),
    ('telecommunications'),
    ('energy'),
    ('cybersecurity'),
    ('mechanical engineering'),
    ('electrical engineering'),
    ('public health'),
    ('epidemiology'),
    ('nutrition'),
    ('architecture'),
    ('sculpture'),
    ('drawing'),
    ('painting'),
    ('printmaking'),
    ('photography'),
    ('music'),
    ('sports'),
    ('theater'),
    ('dance'),
    ('film'),
    ('fashion'),
    ('literature'),
    ('poetry'),
    ('drama'),
    ('science fiction'),
    ('fantasy'),
    ('horror'),
    ('mystery'),
    ('geography'),
    ('biography'),
    ('genealogy'),
    ('archaeology'),
    ('colonialism'),
    ('ancient history'),
    ('medieval history'),
    ('modern history'),
    ('historiography')
ON CONFLICT (name) DO NOTHING;
